##version: '3'
#version: '2'
#services:
#    oauth2-postgresql:
#        image: postgres
#        volumes:
#            - ~/volumes/oauth2/mysql/:/var/lib/postgresql/data
#        ports:
#            - 5432:5432


# Use postgres/example user/password credentials
#version: '3.1'
#
#services:
#    db:
#        image: postgres
#        volumes:
#            - ~/volumes/oauth2/mysql/:/var/lib/postgresql/data
#        restart: always
#        environment:
#            POSTGRES_PASSWORD: example
#
#    adminer:
#        image: adminer
#        restart: always
#        ports:
#            - 8083:8083

version: '3'

services:
    db:
        image: postgres:latest
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
            POSTGRES_DB: 'oauth2'
#        volumes:
#            - database_data:/var/lib/postgresql/data


volumes:
    database_data:
        driver: local