version: '3'

services:
    db:
        image: postgres:latest
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
            POSTGRES_DB: 'oauth2'
        volumes:
            - database_data:/var/lib/postgresql/data


volumes:
    database_data:
        driver: local