spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2
    username: postgres
    password: postgres
    # always embedded never
    initialization-mode: never
#    initialization-mode: always
  jpa:
    show-sql: true

  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Hibernate ddl auto (create, create-drop, validate, update, none)
    hibernate:
      ddl-auto: none

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: "*"
